### ISSUE TITLE
Need to update doc for notebook 4 for changes to VCAP

### ISSUE THREAD

**Issue by smchamberlin** [ibm-watson-data-lab/advo-beta-review#1]
Hi, notebook 4 documentation should be updated because if the instructions are followed exactly it won't work.  I think this is because of some changes that were added to support a bound redis service in the VCAP.

I took one of my existing redis services and put it into the REDIS_URL environment variable of the application as instructed, but no data was flowing in.  I then discovered that the "Deploy to Bluemix" button actually includes its own Redis service in the VCAP and the data is read from that one instead of what is put into REDIS_URL (I verified this in the code, too - priority goes to the bound service).  So 1) You don't need to create a Redis database if you use the convenient "Deploy to Bluemix" button, and 2) You don't need to set the REDIS_URL var if you use this button, as it will use the bound service, and 3) The info that you should put into the mock data script (or anywhere it asks for Redis credentials) should come directly from this VCAP - so maybe include instructions on how to pull that info from the VCAP.

**Comment by smchamberlin** [comment]
Also tracked here:
https://github.ibm.com/wdp-infra/cross-platform-integration/issues/48

**Comment by ptitzler** [comment]
> I then discovered that the "Deploy to Bluemix" button actually includes its own Redis service in the VCAP and the data is read from that one instead of what is put into REDIS_URL (I verified this in the code, too - priority goes to the bound service).  
We've changed the application's default behavior (https://github.com/ibm-watson-data-lab/advo-beta-dashboard/pull/3) to connect to `REDIS_URL` if the variable is set. Only if it is not set will the application attempt to connect to one of the Redis instances that might have been bound to the application in Bluemix.

**Comment by ptitzler** [comment]
For *Beta customers* there is no longer a need to set the `REDIS_URL` environment variable when the D2BM button is used because the application automatically binds the pre-provisioned service instance named `ComposeForRedis-WDPBeta`. 
Advanced users can still use a different Redis instance by defining `REDIS_URL` (see previous comment), but the instructions on how to do that have been removed.
